CREATE TABLE temp_regimen (
  id int(4) NOT NULL AUTO_INCREMENT,
  regimen_code varchar(20) NOT NULL,
  regimen_desc text NOT NULL,
  category int(11) DEFAULT NULL,
  line varchar(4) NOT NULL,
  type_of_service varchar(20) NOT NULL,
  remarks varchar(30) NOT NULL,
  enabled varchar(4) NOT NULL DEFAULT '1',
  source varchar(10) NOT NULL DEFAULT '0',
  optimality varchar(10) NOT NULL DEFAULT '1',
  Merged_To varchar(50) NOT NULL,
  map int(11) NOT NULL,
  ccc_store_sp int(11) NOT NULL DEFAULT '2',
  PRIMARY KEY (id)
)//
INSERT INTO temp_regimen (regimen_code, regimen_desc, category, line, type_of_service, remarks, enabled, source, optimality, Merged_To, map, ccc_store_sp) VALUES
('AF1D',	'AZT + 3TC + DTG',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AF1E',	'AZT + 3TC + LPV/r',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AF1F',	'AZT + 3TC + ATV/r',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AF2D',	'TDF + 3TC + ATV/r',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AF2F',	'TDF + 3TC + LPV/r',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AF5X',	'Any other 1st line Adult regimens',	2,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AS1C',	'AZT + 3TC + DTG',	3,	'2',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AS5C',	'ABC + 3TC + DTG',	3,	'2',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AT2D',	'TDF+3TC+DTG+DRV+RTV',	13,	'3',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AT2E',	'TDF+3TC+RAL+DRV+RTV',	13,	'3',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('AT2F',	'TDF+3TC+DTG+ETV+DRV+RTV',	13,	'3',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('ATPT1A', 'Adult patients (=>15 Yrs) newly started on IPT in the month',	11,	'0',	'4',	'',	'1',	'0',	'1',	'',	0,	2),
('ATPT1B', 'Adult patients (=>15 Yrs) newly started on 3HP in the month',	11,	'0',	'4',	'',	'1',	'0',	'1',	'',	0,	2),
('CF2F',	'ABC + 3TC + RAL',	5,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CF2G',	'ABC+3TC+DTG',	5,	'1',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CS1C',	'AZT + 3TC + DRV+RTV+RAL',	6,	'2',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CS2D',	'ABC + 3TC + DRV+RTV+RAL',	6,	'2',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CS4X',	'Any other 2nd line Paediatric regimens',	6,	'2',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CT1H',	'AZT + 3TC + DRV+RTV+RAL',	13,	'13',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CT2D',	'ABC + 3TC + DRV+RTV+RAL',	13,	'13',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CT3X',	'Any other 3rd line Paediatric regimens',	13,	'13',	'1',	'',	'1',	'0',	'1',	'',	0,	2),
('CTPT1A', 'Paed patients (<15 Yrs) newly started on IPT in the month',	11,	'0',	'4',	'',	'1',	'0',	'1',	'',	0,	2),
('CTPT1B', 'Paed patients (<15 Yrs) newly started on 3HP in the month',	11,	'0',	'4',	'',	'1',	'0',	'1',	'',	0,	2),
('OI6A',	'Adult patients (=>15 Yrs) on Amphotericin B treatment in the month',	11,	'0',	'4',	'',	'1',	'0',	'1',	'',	0,	2),
('PA3D',	'TDF + 3TC + DTG (Adult PEP)',	8,	'0',	'2',	'',	'1',	'0',	'1',	'',	0,	2),
('PC3B',	'ABC + 3TC + RAL (Paed PEP)',	9,	'0',	'2',	'',	'1',	'0',	'1',	'',	0,	2),
('PM12',	'PMTCT HAART: TDF + 3TC + DTG',	1,	'0',	'3',	'',	'1',	'0',	'1',	'',	0,	2),
('PM13',	'PMTCT HAART: AZT + 3TC + DTG',	1,	'0',	'3',	'',	'1',	'0',	'1',	'',	0,	2),
('PM14',	'PMTCT HAART: ABC + 3TC + DTG',	1,	'0',	'3',	'',	'1',	'0',	'1',	'',	0,	2),
('PM15',	'PMTCT HAART: ABC + 3TC + EFV',	1,	'0',	'3',	'',	'1',	'0',	'1',	'',	0,	2)//
INSERT INTO regimen (regimen_code, regimen_desc, category, line, type_of_service, remarks, enabled, source, optimality, Merged_To, map, ccc_store_sp) 
select regimen_code, regimen_desc, category, line, type_of_service, remarks, enabled, source, optimality, Merged_To, map, ccc_store_sp from temp_regimen where regimen_code not in (select regimen_code from regimen)  //

 drop TABLE temp_regimen//