UPDATE dhis_elements SET target_id = 12 WHERE target_report = 'F-CDRR' AND dhis_code =  'Bv08ScvBzZy'//
UPDATE dhis_elements SET target_id = 246 WHERE target_report = 'F-CDRR' AND dhis_code =  'WeA3sq0ELOE'//
UPDATE dhis_elements SET target_id = 173 WHERE target_report = 'F-CDRR' AND dhis_code =  'hnMei2LGuhw'//
UPDATE dhis_elements SET target_id = 195 WHERE target_report = 'F-CDRR' AND dhis_code =  'Lo1lUEHEXap'//
UPDATE dhis_elements SET target_id = 248 WHERE target_report = 'F-CDRR' AND dhis_code =  'Qr8Hx7Nl02R'//
UPDATE dhis_elements SET target_id = 7 WHERE target_report = 'F-CDRR' AND dhis_code =  'JfkxhCPe29t'//
UPDATE dhis_elements SET target_id = 8 WHERE target_report = 'F-CDRR' AND dhis_code =  'jC1clm8DHjU'//
UPDATE dhis_elements SET target_id = 15 WHERE target_report = 'F-CDRR' AND dhis_code =  'GjYg7sEHVAx'//
UPDATE dhis_elements SET target_id = 9 WHERE target_report = 'F-CDRR' AND dhis_code =  'Fo2gnhRx1eB'//
UPDATE dhis_elements SET target_id = 198 WHERE target_report = 'F-CDRR' AND dhis_code =  'dsZqocFWAqm'//
UPDATE dhis_elements SET target_id = 244 WHERE target_report = 'F-CDRR' AND dhis_code =  'FE6o5uZ6Ey3'//
UPDATE dhis_elements SET target_id = 245 WHERE target_report = 'F-CDRR' AND dhis_code =  'Ovk1BBcACSN'//
UPDATE dhis_elements SET target_id = 259 WHERE target_report = 'F-CDRR' AND dhis_code =  'YpjdjMD6yeC'//
UPDATE dhis_elements SET target_id = 258 WHERE target_report = 'F-CDRR' AND dhis_code =  'wJTbaU9jnf2'//
UPDATE dhis_elements SET target_id = 3 WHERE target_report = 'F-CDRR' AND dhis_code =  'MtiBOPPd7Ke'//
UPDATE dhis_elements SET target_id = 4 WHERE target_report = 'F-CDRR' AND dhis_code =  'VJMNX2JtVAL'//
UPDATE dhis_elements SET target_id = 10 WHERE target_report = 'F-CDRR' AND dhis_code =  'lMHWiV1wfzU'//
UPDATE dhis_elements SET target_id = 11 WHERE target_report = 'F-CDRR' AND dhis_code =  'L9VlZFQZGbv'//
UPDATE dhis_elements SET target_id = 2 WHERE target_report = 'F-CDRR' AND dhis_code =  'YUbsR6vuIVF'//
UPDATE dhis_elements SET target_id = 1 WHERE target_report = 'F-CDRR' AND dhis_code =  'ZPdNDKh0jtf'//
UPDATE dhis_elements SET target_id = 0 WHERE target_report = 'F-CDRR' AND dhis_code =  'vBNVMx60V31'//
UPDATE dhis_elements SET target_id = 165 WHERE target_report = 'F-CDRR' AND dhis_code =  'ZYYcDSXFHcq'//
UPDATE dhis_elements SET target_id = 45 WHERE target_report = 'F-CDRR' AND dhis_code =  'Ywi6QrCf4wp'//
UPDATE dhis_elements SET target_id = 37 WHERE target_report = 'F-CDRR' AND dhis_code =  'uYwZjUIeoY2'//
UPDATE dhis_elements SET target_id = 38 WHERE target_report = 'F-CDRR' AND dhis_code =  'rS62iKZ6Idq'//
UPDATE dhis_elements SET target_id = 43 WHERE target_report = 'F-CDRR' AND dhis_code =  'BHlhxD6Wjct'//
UPDATE dhis_elements SET target_id = 249 WHERE target_report = 'F-CDRR' AND dhis_code =  'KnOB8nSo99l'//
UPDATE dhis_elements SET target_id = 227 WHERE target_report = 'F-CDRR' AND dhis_code =  'Fmu24faR6RP'//
UPDATE dhis_elements SET target_id = 231 WHERE target_report = 'F-CDRR' AND dhis_code =  'YvUG4Tj5pBB'//
UPDATE dhis_elements SET target_id = 232 WHERE target_report = 'F-CDRR' AND dhis_code =  'Zp4GO6RalC3'//
UPDATE dhis_elements SET target_id = 25 WHERE target_report = 'F-CDRR' AND dhis_code =  'FWfv9nwqQNj'//
UPDATE dhis_elements SET target_id = 213 WHERE target_report = 'F-CDRR' AND dhis_code =  'CUkg2rMIBqV'//
UPDATE dhis_elements SET target_id = 26 WHERE target_report = 'F-CDRR' AND dhis_code =  'k820rGmrG7y'//
UPDATE dhis_elements SET target_id = 263 WHERE target_report = 'F-CDRR' AND dhis_code =  'bNwb0BQTiXu'//
UPDATE dhis_elements SET target_id = 28 WHERE target_report = 'F-CDRR' AND dhis_code =  'GTqdnEoYWpl'//
UPDATE dhis_elements SET target_id = 260 WHERE target_report = 'F-CDRR' AND dhis_code =  'w96pwQ6povd'//
UPDATE dhis_elements SET target_id = 147 WHERE target_report = 'F-CDRR' AND dhis_code =  'LdqZPGOt7px'//
UPDATE dhis_elements SET target_id = 35 WHERE target_report = 'F-CDRR' AND dhis_code =  'U3h59Gd6zNP'//
UPDATE dhis_elements SET target_id = 17 WHERE target_report = 'F-CDRR' AND dhis_code =  'cgSXbyWnsji'//
UPDATE dhis_elements SET target_id = 16 WHERE target_report = 'F-CDRR' AND dhis_code =  'CV5vmItEeGO'//
UPDATE dhis_elements SET target_id = 255 WHERE target_report = 'F-CDRR' AND dhis_code =  'XYarFhtrZnM'//
UPDATE dhis_elements SET target_id = 157 WHERE target_report = 'F-CDRR' AND dhis_code =  'ow27FKynLOP'//
UPDATE dhis_elements SET target_id = 264 WHERE target_report = 'F-CDRR' AND dhis_code =  'hI5dsFlNwro'//
UPDATE dhis_elements SET target_id = 130 WHERE target_report = 'F-CDRR' AND dhis_code =  'bjqajaEgKDD'//
UPDATE dhis_elements SET target_id = 242 WHERE target_report = 'F-CDRR' AND dhis_code =  'ScMZvEURp0k'//
UPDATE dhis_elements SET target_id = 256 WHERE target_report = 'F-CDRR' AND dhis_code =  'rgrECRA0XVz'//
UPDATE dhis_elements SET target_id = 253 WHERE target_report = 'F-CDRR' AND dhis_code =  'noIMGcbffat'//
UPDATE dhis_elements SET target_id = 47 WHERE target_report = 'F-CDRR' AND dhis_code =  'nReJj3EEIHt'//
UPDATE dhis_elements SET target_id = 257 WHERE target_report = 'F-CDRR' AND dhis_code =  'gjOJC5nWO9W'//
UPDATE dhis_elements SET target_id = 265 WHERE target_report = 'F-CDRR' AND dhis_code =  'y849186w1rj'//
UPDATE dhis_elements SET target_id = 266 WHERE target_report = 'F-CDRR' AND dhis_code =  'orN14YLwwZM'//
UPDATE dhis_elements SET target_id = 267 WHERE target_report = 'F-CDRR' AND dhis_code =  'ms3ICb7Ic6Z'//
UPDATE dhis_elements SET target_id = 250 WHERE target_report = 'F-CDRR' AND dhis_code =  'qvS7TkgQO1f'//
UPDATE dhis_elements SET target_id = 261 WHERE target_report = 'F-CDRR' AND dhis_code =  'SeDTXsB8p8g'//
UPDATE dhis_elements SET target_id = 215 WHERE target_report = 'F-CDRR' AND dhis_code =  'aGYM59Vptun'//
UPDATE dhis_elements SET target_id = 216 WHERE target_report = 'F-CDRR' AND dhis_code =  'q7xXQuGgvgB'//
UPDATE dhis_elements SET target_id = 268 WHERE target_report = 'F-CDRR' AND dhis_code =  'i7MzGhzg6VJ'//
UPDATE dhis_elements SET target_id = 269 WHERE target_report = 'F-CDRR' AND dhis_code =  'POCEHFzbrPN'//
UPDATE dhis_elements SET target_id = 259 WHERE target_report = 'F-CDRR' AND dhis_code =  'EqZyS1EUSQc'//
UPDATE dhis_elements SET target_id = 258 WHERE target_report = 'F-CDRR' AND dhis_code =  'H6HgMLW2tWl'//
UPDATE dhis_elements SET target_id = 270 WHERE target_report = 'F-CDRR' AND dhis_code =  'KRY9yB58imr'//