UPDATE regimen SET regimen_desc= 'AF1A | AZT + 3TC + NVP' WHERE regimen_code like '%AF1A%'//
UPDATE regimen SET regimen_desc= 'AF1B | AZT + 3TC + EFV' WHERE regimen_code like '%AF1B%'//
UPDATE regimen SET regimen_desc= 'AF2A | TDF + 3TC + NVP' WHERE regimen_code like '%AF2A%'//
UPDATE regimen SET regimen_desc= 'AF2B | TDF + 3TC + EFV' WHERE regimen_code like '%AF2B%'//
UPDATE regimen SET regimen_desc= 'AF2E | TDF + 3TC + DTG' WHERE regimen_code like '%AF2E%'//
UPDATE regimen SET regimen_desc= 'AS1B | AZT + 3TC + ATV/r' WHERE regimen_code like '%AS1B%'//
UPDATE regimen SET regimen_desc= 'AS2C | TDF + 3TC + ATV/r' WHERE regimen_code like '%AS2C%'//
UPDATE regimen SET regimen_desc= 'AF1D | AZT + 3TC + DTG' WHERE regimen_code like '%AF1D%'//
UPDATE regimen SET regimen_desc= 'AF2D | TDF + 3TC + ATV/r' WHERE regimen_code like '%AF2D%'//
UPDATE regimen SET regimen_desc= 'AF2E | TDF + 3TC + DTG' WHERE regimen_code like '%AF2E%'//
UPDATE regimen SET regimen_desc= 'AF2F | TDF + 3TC + LPV/r (1L Adults <40kg)' WHERE regimen_code like '%AF2F%'//
UPDATE regimen SET regimen_desc= 'AF2G | TDF + 3TC + RAL (PWIDs intoIerant to ATV)' WHERE regimen_code like '%AF2G%'//
UPDATE regimen SET regimen_desc= 'AF2H | TDF + FTC + ATV/r' WHERE regimen_code like '%AF2H%'//
UPDATE regimen SET regimen_desc= 'AF4C | ABC + 3TC + DTG' WHERE regimen_code like '%AF4C%'//
UPDATE regimen SET regimen_desc= 'AT1D | RAL + DRV + RTV + ETV + other backbone ARVs' WHERE regimen_code like '%AT1D%'//
UPDATE regimen SET regimen_desc= 'AT1E | RAL + ETV + other backbone ARVs' WHERE regimen_code like '%AT1E%'//
UPDATE regimen SET regimen_desc= 'AT1F | RAL + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%AT1F%'//
UPDATE regimen SET regimen_desc= 'AT1G | RAL + other backbone ARVs (2nd Line patients failing treatment)' WHERE regimen_code like '%AT1G%'//
UPDATE regimen SET regimen_desc= 'AT2B | ETV + other backbone ARVs' WHERE regimen_code like '%AT2B%'//
UPDATE regimen SET regimen_desc= 'AT2C | ETV + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%AT2C%'//
UPDATE regimen SET regimen_desc= 'AT3A | DRV + RTV + other backbone ARVs' WHERE regimen_code like '%AT3A%'//
UPDATE regimen SET regimen_desc= 'AT4A | DTG + DRV + RTV + ETV + other backbone ARVs' WHERE regimen_code like '%AT4A%'//
UPDATE regimen SET regimen_desc= 'AT4B | DTG + ETV + other backbone ARVs' WHERE regimen_code like '%AT4B%'//
UPDATE regimen SET regimen_desc= 'AT4C | DTG + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%AT4C%'//
UPDATE regimen SET regimen_desc= 'AT4D | DTG + other backbone ARVs (2nd Line patients failing treatment)' WHERE regimen_code like '%AT4D%'//
UPDATE regimen SET regimen_desc= 'CF2B | ABC + 3TC + EFV' WHERE regimen_code like '%CF2B%'//
UPDATE regimen SET regimen_desc= 'AS2A | TDF + 3TC + LPV/r' WHERE regimen_code like '%AS2A%'//
UPDATE regimen SET regimen_desc= 'CF2D | ABC + 3TC + LPV/r' WHERE regimen_code like '%CF2D%'//
UPDATE regimen SET regimen_desc= 'AF3A | d4T + 3TC + NVP' WHERE regimen_code like '%AF3A%'//
UPDATE regimen SET regimen_desc= 'AF3B | d4T + 3TC + EFV' WHERE regimen_code like '%AF3B%'//
UPDATE regimen SET regimen_desc= 'AF4A | ABC + 3TC + NVP' WHERE regimen_code like '%AF4A%'//
UPDATE regimen SET regimen_desc= 'AF4B | ABC + 3TC + EFV' WHERE regimen_code like '%AF4B%'//
UPDATE regimen SET regimen_desc= 'AF5X | All other 1st line Adult regimens' WHERE regimen_code like '%AF5X%'//
UPDATE regimen SET regimen_desc= 'AS1A | AZT + 3TC + LPV/r' WHERE regimen_code like '%AS1A%'//
UPDATE regimen SET regimen_desc= 'AS5A | ABC + 3TC + LPV/r' WHERE regimen_code like '%AS5A%'//
UPDATE regimen SET regimen_desc= 'AS5B | ABC + 3TC + ATV/r' WHERE regimen_code like '%AS5B%'//
UPDATE regimen SET regimen_desc= 'AS6X | All other 2nd line Adult regimens' WHERE regimen_code like '%AS6X%'//
UPDATE regimen SET regimen_desc= 'AT1A | RAL + 3TC + DRV + RTV' WHERE regimen_code like '%AT1A%'//
UPDATE regimen SET regimen_desc= 'AT1B | RAL + 3TC + DRV + RTV + AZT' WHERE regimen_code like '%AT1B%'//
UPDATE regimen SET regimen_desc= 'AT1C | RAL + 3TC + DRV + RTV + TDF' WHERE regimen_code like '%AT1C%'//
UPDATE regimen SET regimen_desc= 'AT2A | ETV + 3TC + DRV + RTV' WHERE regimen_code like '%AT2A%'//
UPDATE regimen SET regimen_desc= 'AT2X | All other 3rd line Adult regimens' WHERE regimen_code like '%AT2X%'//
UPDATE regimen SET regimen_desc= 'CF1A | AZT + 3TC + NVP' WHERE regimen_code like '%CF1A%'//
UPDATE regimen SET regimen_desc= 'CF1B | AZT + 3TC + EFV' WHERE regimen_code like '%CF1B%'//
UPDATE regimen SET regimen_desc= 'CF1C | AZT + 3TC + LPV/r' WHERE regimen_code like '%CF1C%'//
UPDATE regimen SET regimen_desc= 'CF1D | AZT + 3TC + ATV/r' WHERE regimen_code like '%CF1D%'//
UPDATE regimen SET regimen_desc= 'CF2A | ABC + 3TC + NVP' WHERE regimen_code like '%CF2A%'//
UPDATE regimen SET regimen_desc= 'CF2E | ABC + 3TC + ATV/r' WHERE regimen_code like '%CF2E%'//
UPDATE regimen SET regimen_desc= 'CF3A | d4T + 3TC + NVP for children weighing >= 25kg' WHERE regimen_code like '%CF3A%'//
UPDATE regimen SET regimen_desc= 'CF3B | d4T + 3TC + EFV for children weighing >= 25kg' WHERE regimen_code like '%CF3B%'//
UPDATE regimen SET regimen_desc= 'CF4A | TDF + 3TC + NVP' WHERE regimen_code like '%CF4A%'//
UPDATE regimen SET regimen_desc= 'CF4B | TDF + 3TC + EFV' WHERE regimen_code like '%CF4B%'//
UPDATE regimen SET regimen_desc= 'CF4C | TDF + 3TC + LPV/r' WHERE regimen_code like '%CF4C%'//
UPDATE regimen SET regimen_desc= 'CF4D | TDF + 3TC + ATV/r' WHERE regimen_code like '%CF4D%'//
UPDATE regimen SET regimen_desc= 'CF5X | All other 1st line Paediatric regimens' WHERE regimen_code like '%CF5X%'//
UPDATE regimen SET regimen_desc= 'CS1A | AZT + 3TC + LPV/r' WHERE regimen_code like '%CS1A%'//
UPDATE regimen SET regimen_desc= 'CS1B | AZT + 3TC + ATV/r' WHERE regimen_code like '%CS1B%'//
UPDATE regimen SET regimen_desc= 'CS2A | ABC + 3TC + LPV/r' WHERE regimen_code like '%CS2A%'//
UPDATE regimen SET regimen_desc= 'CS2C | ABC + 3TC + ATV/r' WHERE regimen_code like '%CS2C%'//
UPDATE regimen SET regimen_desc= 'CS4X | All other 2nd line Paediatric regimens' WHERE regimen_code like '%CS4X%'//
UPDATE regimen SET regimen_desc= 'CT1A | RAL + 3TC + DRV + RTV' WHERE regimen_code like '%CT1A%'//
UPDATE regimen SET regimen_desc= 'CT1B | RAL + 3TC + DRV + RTV + AZT' WHERE regimen_code like '%CT1B%'//
UPDATE regimen SET regimen_desc= 'CT1C | RAL + 3TC + DRV + RTV + ABC' WHERE regimen_code like '%CT1C%'//
UPDATE regimen SET regimen_desc= 'CT2A | ETV + 3TC + DRV + RTV' WHERE regimen_code like '%CT2A%'//
UPDATE regimen SET regimen_desc= 'CT3X | All other 3rd line Paediatric regimens' WHERE regimen_code like '%CT3X%'//
UPDATE regimen SET regimen_desc= 'CS2B | ABC+3TC+DTG' WHERE regimen_code like '%CS2B%'//
UPDATE regimen SET regimen_desc= 'AS2B | TDF + 3TC + DTG' WHERE regimen_code like '%AS2B%'//
UPDATE regimen SET regimen_desc= 'CF4E | TDF + 3TC + DTG' WHERE regimen_code like '%CF4E%'//
UPDATE regimen SET regimen_desc= 'CF2G | ABC+3TC+DTG' WHERE regimen_code like '%CF2G%'//
UPDATE regimen SET regimen_desc= 'CS1C | AZT + 3TC + DRV+RTV+RAL' WHERE regimen_code like '%CS1C%'//
UPDATE regimen SET regimen_desc= 'CS2D | ABC + 3TC + DRV+RTV+RAL' WHERE regimen_code like '%CS2D%'//
UPDATE regimen SET regimen_desc= 'CT1H | AZT + 3TC + DRV+RTV+RAL' WHERE regimen_code like '%CT1H%'//
UPDATE regimen SET regimen_desc= 'CT2D | ABC + 3TC + DRV+RTV+RAL' WHERE regimen_code like '%CT2D%'//
UPDATE regimen SET regimen_desc= 'CF1E | AZT + 3TC + RAL' WHERE regimen_code like '%CF1E%'//
UPDATE regimen SET regimen_desc= 'CF2F | ABC + 3TC + RAL' WHERE regimen_code like '%CF2F%'//
UPDATE regimen SET regimen_desc= 'CT1D | RAL + DRV + RTV + ETV + other backbone ARVs' WHERE regimen_code like '%CT1D%'//
UPDATE regimen SET regimen_desc= 'CT1E | RAL + ETV + other backbone ARVs' WHERE regimen_code like '%CT1E%'//
UPDATE regimen SET regimen_desc= 'CT1F | RAL + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%CT1F%'//
UPDATE regimen SET regimen_desc= 'CT1G | RAL + other backbone ARVs' WHERE regimen_code like '%CT1G%'//
UPDATE regimen SET regimen_desc= 'CT2B | ETV + other backbone ARVs' WHERE regimen_code like '%CT2B%'//
UPDATE regimen SET regimen_desc= 'CT2C | ETV + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%CT2C%'//
UPDATE regimen SET regimen_desc= 'CT3A | DRV + RTV + other backbone ARVs' WHERE regimen_code like '%CT3A%'//
UPDATE regimen SET regimen_desc= 'CT4A | DTG + DRV + RTV + ETV + other backbone ARVs' WHERE regimen_code like '%CT4A%'//
UPDATE regimen SET regimen_desc= 'CT4B | DTG + ETV + other backbone ARVs' WHERE regimen_code like '%CT4B%'//
UPDATE regimen SET regimen_desc= 'CT4C | DTG + DRV + RTV + other backbone ARVs' WHERE regimen_code like '%CT4C%'//
UPDATE regimen SET regimen_desc= 'AS3A | ABC + 3TC + LPV/r' WHERE regimen_code like '%AS3A%'//
UPDATE regimen SET regimen_desc= 'AS4A | d4T + 3TC + LPV/r ' WHERE regimen_code like '%AS4A%'//
UPDATE regimen SET regimen_desc= 'CF2C | ABC + 3TC + AZT' WHERE regimen_code like '%CF2C%'//
UPDATE regimen SET regimen_desc= 'CS3A | d4T + 3TC + LPV/r' WHERE regimen_code like '%CS3A%'//
UPDATE regimen SET regimen_desc= 'AS3B | ABC + ddI + LPV/r' WHERE regimen_code like '%AS3B%'//
UPDATE regimen SET regimen_desc= 'AF1E | AZT + 3TC + LPV/r' WHERE regimen_code like '%AF1E%'//
UPDATE regimen SET regimen_desc= 'AF1F | AZT + 3TC + ATV/r' WHERE regimen_code like '%AF1F%'//
UPDATE regimen SET regimen_desc= 'AS1C | AZT + 3TC + DTG' WHERE regimen_code like '%AS1C%'//
UPDATE regimen SET regimen_desc= 'AS5C | ABC + 3TC + DTG' WHERE regimen_code like '%AS5C%'//
UPDATE regimen SET regimen_desc= 'AT2D | TDF+3TC+DTG+DRV+RTV' WHERE regimen_code like '%AT2D%'//
UPDATE regimen SET regimen_desc= 'AT2E | TDF+3TC+RAL+DRV+RTV' WHERE regimen_code like '%AT2E%'//
UPDATE regimen SET regimen_desc= 'AT2F | TDF+3TC+DTG+ETV+DRV+RTV' WHERE regimen_code like '%AT2F%'//
UPDATE regimen SET regimen_desc= 'CT4D | DTG + other backbone ARVs' WHERE regimen_code like '%CT4D%'//
UPDATE regimen SET regimen_desc= 'AF1C | AZT + 3TC + ABC' WHERE regimen_code like '%AF1C%'//
UPDATE regimen SET regimen_desc= 'AF2C | TDF + 3TC + AZT' WHERE regimen_code like '%AF2C%'//
UPDATE regimen SET regimen_desc= 'AF3C | d4T + 3TC + ABC' WHERE regimen_code like '%AF3C%'//
UPDATE regimen SET regimen_desc= 'CM3N | New patients with CM on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%CM3N%'//
UPDATE regimen SET regimen_desc= 'CM3R | Revisit patients with CM on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%CM3R%'//
UPDATE regimen SET regimen_desc= 'OC3N | New patients with OC on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%OC3N%'//
UPDATE regimen SET regimen_desc= 'OC3R | Revisit patients with OC on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%OC3R%'//
UPDATE regimen SET regimen_desc= 'OI1A | Adult patients (=>15 Yrs) on Cotrimoxazole prophylaxis' WHERE regimen_code like '%OI1A%'//
UPDATE regimen SET regimen_desc= 'OI1C | Paediatric patients (<15 Yrs) on Cotrimoxazole prophylaxis' WHERE regimen_code like '%OI1C%'//
UPDATE regimen SET regimen_desc= 'OI2A | Adult patients (=>15 Yrs) on Dapsone prophylaxis' WHERE regimen_code like '%OI2A%'//
UPDATE regimen SET regimen_desc= 'OI2C | Paediatric patients (<15 Yrs) on Dapsone prophylaxis' WHERE regimen_code like '%OI2C%'//
UPDATE regimen SET regimen_desc= 'OI3A | Adult patients on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%OI3A%'//
UPDATE regimen SET regimen_desc= 'OI3C | Paed patients on Diflucan (For Diflucan Donation Program ONLY)' WHERE regimen_code like '%OI3C%'//
UPDATE regimen SET regimen_desc= 'OI4A | Adult patients (=>15 Yrs) on Isoniazid prophylaxis' WHERE regimen_code like '%OI4A%'//
UPDATE regimen SET regimen_desc= 'OI4C | Paediatric patients (<15 Yrs) on Isoniazid prophylaxis' WHERE regimen_code like '%OI4C%'//
UPDATE regimen SET regimen_desc= 'PA1B | AZT + 3TC + LPV/r (Adult PEP)' WHERE regimen_code like '%PA1B%'//
UPDATE regimen SET regimen_desc= 'PA1C | AZT + 3TC + ATV/r (Adult PEP)' WHERE regimen_code like '%PA1C%'//
UPDATE regimen SET regimen_desc= 'PA3B | TDF + 3TC + LPV/r (Adult PEP)' WHERE regimen_code like '%PA3B%'//
UPDATE regimen SET regimen_desc= 'PA3C | TDF + 3TC + ATV/r (Adult PEP)' WHERE regimen_code like '%PA3C%'//
UPDATE regimen SET regimen_desc= 'PA4X | All other PEP regimens for Adults' WHERE regimen_code like '%PA4X%'//
UPDATE regimen SET regimen_desc= 'PC4X | All other PEP regimens for Children' WHERE regimen_code like '%PC4X%'//
UPDATE regimen SET regimen_desc= 'PC6 | NVP Liquid OD for 12 weeks ' WHERE regimen_code like '%PC6%'//
UPDATE regimen SET regimen_desc= 'PM2 | NVP 200mg stat + AZT 600mg stat (or 300mg BD) + 3TC 150mg BD during labour then 1 tab of AZT/3TC 300mg/150mg BD for one week post-partum' WHERE regimen_code like '%PM2%'//
UPDATE regimen SET regimen_desc= 'PM3 | PMTCT HAART: AZT + 3TC + NVP' WHERE regimen_code like '%PM3%'//
UPDATE regimen SET regimen_desc= 'PM4 | PMTCT HAART: AZT + 3TC + EFV' WHERE regimen_code like '%PM4%'//
UPDATE regimen SET regimen_desc= 'PM5 | PMTCT HAART: AZT + 3TC + LPV/r' WHERE regimen_code like '%PM5%'//
UPDATE regimen SET regimen_desc= 'PM6 | PMTCT HAART: TDF + 3TC + NVP' WHERE regimen_code like '%PM6%'//
UPDATE regimen SET regimen_desc= 'PM7 | PMTCT HAART: TDF + 3TC + LPV/r' WHERE regimen_code like '%PM7%'//
UPDATE regimen SET regimen_desc= 'PM9 | PMTCT HAART: TDF + 3TC + EFV' WHERE regimen_code like '%PM9%'//
UPDATE regimen SET regimen_desc= 'PRP1A | TDF + FTC (PrEP)' WHERE regimen_code like '%PRP1A%'//
UPDATE regimen SET regimen_desc= 'HPB1A | TDF + 3TC (HIV-ve HepB patients)' WHERE regimen_code like '%HPB1A%'//
UPDATE regimen SET regimen_desc= 'HPB1B | TDF + FTC (HIV-ve HepB patients)' WHERE regimen_code like '%HPB1B%'//
UPDATE regimen SET regimen_desc= 'OI4AN | Adult patients (=>15 Yrs) newly started on IPT in the month' WHERE regimen_code like '%OI4AN%'//
UPDATE regimen SET regimen_desc= 'OI4CN | Paed patients (<15 Yrs) newly started on IPT in the month' WHERE regimen_code like '%OI4CN%'//
UPDATE regimen SET regimen_desc= 'OI5A | Adult patients (=>15 Yrs) on Fluconazole in the month' WHERE regimen_code like '%OI5A%'//
UPDATE regimen SET regimen_desc= 'OI5C | Paed patients (<15 Yrs) on Fluconazole in the month' WHERE regimen_code like '%OI5C%'//
UPDATE regimen SET regimen_desc= 'PC5 | 3TC Liquid BD' WHERE regimen_code like '%PC5%'//
UPDATE regimen SET regimen_desc= 'PC7 | AZT liquid BID + NVP liquid OD for 6 weeks then NVP liquid OD for 6 weeks' WHERE regimen_code like '%PC7%'//
UPDATE regimen SET regimen_desc= 'PC8 | AZT liquid BID + NVP liquid OD for 6 weeks then NVP liquid OD until 6 weeks after complete cessation of Breastfeeding (mother NOT on ART)' WHERE regimen_code like '%PC8%'//
UPDATE regimen SET regimen_desc= 'PC9 | AZT liquid BID for 12 weeks' WHERE regimen_code like '%PC9%'//
UPDATE regimen SET regimen_desc= 'PRP1B | TDF + 3TC (PrEP)' WHERE regimen_code like '%PRP1B%'//
UPDATE regimen SET regimen_desc= 'PRP1C | TDF (PrEP)' WHERE regimen_code like '%PRP1C%'//
UPDATE regimen SET regimen_desc= 'PA1A | AZT + 3TC' WHERE regimen_code like '%PA1A%'//
UPDATE regimen SET regimen_desc= 'PA2A | d4T + 3TC' WHERE regimen_code like '%PA2A%'//
UPDATE regimen SET regimen_desc= 'PA2B | d4T + 3TC + LPV/r' WHERE regimen_code like '%PA2B%'//
UPDATE regimen SET regimen_desc= 'PA3A | TDF + 3TC' WHERE regimen_code like '%PA3A%'//
UPDATE regimen SET regimen_desc= 'PA3D | TDF + 3TC + DTG (Adult PEP)' WHERE regimen_code like '%PA3D%'//
UPDATE regimen SET regimen_desc= 'PM8 | Nevirapine (NVP) Single Dose (SD) 200mg stat' WHERE regimen_code like '%PM8%'//
UPDATE regimen SET regimen_desc= 'PC2A | d4T + 3TC + LPV/r (Paed PEP Option 2)' WHERE regimen_code like '%PC2A%'//
UPDATE regimen SET regimen_desc= 'ATPT1A | Adult patients (=>15 Yrs) newly started on IPT in the month' WHERE regimen_code like '%ATPT1A%'//
UPDATE regimen SET regimen_desc= 'ATPT1B | Adult patients (=>15 Yrs) newly started on 3HP in the month' WHERE regimen_code like '%ATPT1B%'//
UPDATE regimen SET regimen_desc= 'CTPT1A | Paed patients (<15 Yrs) newly started on IPT in the month' WHERE regimen_code like '%CTPT1A%'//
UPDATE regimen SET regimen_desc= 'CTPT1B | Paed patients (<15 Yrs) newly started on 3HP in the month' WHERE regimen_code like '%CTPT1B%'//
UPDATE regimen SET regimen_desc= 'OI6A | Adult patients (=>15 Yrs) on Amphotericin B treatment in the month' WHERE regimen_code like '%OI6A%'//
UPDATE regimen SET regimen_desc= 'PC3B | ABC + 3TC + RAL (Paed PEP)' WHERE regimen_code like '%PC3B%'//
UPDATE regimen SET regimen_desc= 'PC1A | AZT + 3TC + LPV/r (Paed PEP)' WHERE regimen_code like '%PC1A%'//
UPDATE regimen SET regimen_desc= 'PC1X | All other PMTCT regimens for Infants' WHERE regimen_code like '%PC1X%'//
UPDATE regimen SET regimen_desc= 'PC3A | ABC + 3TC + LPV/r (Paed PEP)' WHERE regimen_code like '%PC3A%'//
UPDATE regimen SET regimen_desc= 'PM10 | PMTCT HAART: AZT + 3TC + ATV/r' WHERE regimen_code like '%PM10%'//
UPDATE regimen SET regimen_desc= 'PM11 | PMTCT HAART: TDF + 3TC + ATV/r' WHERE regimen_code like '%PM11%'//
UPDATE regimen SET regimen_desc= 'PM1X | All other PMTCT regimens for Women' WHERE regimen_code like '%PM1X%'//
UPDATE regimen SET regimen_desc= 'PM12 | PMTCT HAART: TDF + 3TC + DTG' WHERE regimen_code like '%PM12%'//
UPDATE regimen SET regimen_desc= 'PM13 | PMTCT HAART: AZT + 3TC + DTG' WHERE regimen_code like '%PM13%'//
UPDATE regimen SET regimen_desc= 'PM14 | PMTCT HAART: ABC + 3TC + DTG' WHERE regimen_code like '%PM14%'//
UPDATE regimen SET regimen_desc= 'PM15 | PMTCT HAART: ABC + 3TC + EFV' WHERE regimen_code like '%PM15%'//
UPDATE regimen SET regimen_desc= 'PC4 | AZT Liquid BD for 6 weeks ' WHERE regimen_code like '%PC4'//
UPDATE regimen SET regimen_desc= 'PC2 | NVP OD for Breastfeeding Infants until 1 week after complete cessation of Breastfeeding ' WHERE regimen_code like '%PC2'//
UPDATE regimen SET regimen_desc= 'PC3 | NVP 2 mg/kg stat + AZT 4mg/kg bd for 6 weeks + 3TC 4mg/kg bd for 1 week' WHERE regimen_code like '%PC3'//
UPDATE regimen SET regimen_desc= 'PC1 | NVP OD up to 6 weeks of age for: (i) Infants born of mothers on HAART (Breastfeeding or not)// (ii) ALL Non-Breastfeeding infants born of mothers not o' WHERE regimen_code like '%PC1'//
UPDATE regimen SET regimen_desc= 'PM1 | AZT 300mg BD (from week 14 to Delivery) then NVP 200mg stat + AZT 600mg stat (or 300mg BD) + 3TC 150mg BD during labour then 1 tab of AZT/3TC 300mg' WHERE regimen_code like '%PM1'//
